from dataclasses import dataclass


@dataclass(frozen=True)
class Indicator:
    indicator_id: str
    name: str
    dimension: str
    indicator_type: str
    keywords: tuple[str, ...]
    common_units: tuple[str, ...] = ()
    is_core: bool = True


FORMAL_INDICATORS = [
    Indicator("e_ghg_total", "温室气体排放总量", "E", "quantitative", ("温室气体排放总量", "碳排放总量", "范围1和范围2", "范围一和范围二"), ("吨二氧化碳当量", "tCO2e")),
    Indicator("e_ghg_scope1", "直接温室气体排放量", "E", "quantitative", ("范围一", "范围1", "直接温室气体排放", "Scope 1"), ("吨二氧化碳当量", "tCO2e")),
    Indicator("e_ghg_scope2", "间接温室气体排放量", "E", "quantitative", ("范围二", "范围2", "间接温室气体排放", "Scope 2"), ("吨二氧化碳当量", "tCO2e")),
    Indicator("e_ghg_scope3", "其他间接温室气体排放量", "E", "quantitative", ("范围三", "范围3", "其他间接温室气体排放", "Scope 3"), ("吨二氧化碳当量", "tCO2e")),
    Indicator("e_ghg_intensity", "温室气体排放强度", "E", "quantitative", ("温室气体排放强度", "碳排放强度", "排放密度"), ("吨二氧化碳当量/万元", "tCO2e/百万元")),
    Indicator("e_carbon_target", "碳减排目标", "E", "qualitative", ("碳减排目标", "减碳目标", "碳中和目标", "双碳目标")),
    Indicator("e_carbon_management", "碳排放管理措施", "E", "qualitative", ("碳排放管理", "碳管理", "温室气体管理", "碳盘查")),
    Indicator("e_climate_risk", "气候风险管理", "E", "qualitative", ("气候风险", "气候变化风险", "气候相关风险", "TCFD")),
    Indicator("e_climate_opportunity", "气候机遇管理", "E", "qualitative", ("气候机遇", "气候变化机遇", "绿色机遇")),
    Indicator("e_energy_total", "能源消耗总量", "E", "quantitative", ("能源消耗总量", "总能源消耗", "综合能源消耗", "能源使用量"), ("兆瓦时", "MWh", "吨标准煤")),
    Indicator("e_energy_intensity", "能源消耗强度", "E", "quantitative", ("能源消耗强度", "能源强度", "单位收入能源消耗"), ("兆瓦时/万元", "吨标准煤/万元")),
    Indicator("e_electricity_total", "耗电量", "E", "quantitative", ("耗电量", "用电量", "电力消耗", "外购电力"), ("千瓦时", "kWh", "兆瓦时")),
    Indicator("e_renewable_energy", "可再生能源使用量", "E", "quantitative", ("可再生能源", "绿色电力", "绿电", "清洁能源"), ("千瓦时", "兆瓦时", "%")),
    Indicator("e_natural_gas", "天然气使用量", "E", "quantitative", ("天然气使用量", "天然气消耗", "天然气"), ("立方米", "万立方米")),
    Indicator("e_fuel_consumption", "燃料消耗量", "E", "quantitative", ("燃料消耗", "汽油", "柴油", "燃油"), ("吨", "升")),
    Indicator("e_water_total", "总用水量", "E", "quantitative", ("总用水量", "用水量", "取水量", "耗水量"), ("吨", "立方米")),
    Indicator("e_water_intensity", "用水强度", "E", "quantitative", ("用水强度", "水资源使用强度", "单位收入用水"), ("吨/万元", "立方米/万元")),
    Indicator("e_recycled_water", "循环用水量", "E", "quantitative", ("循环用水", "回用水", "再生水", "中水回用"), ("吨", "立方米", "%")),
    Indicator("e_wastewater", "废水排放量", "E", "quantitative", ("废水排放", "污水排放", "排水量"), ("吨", "立方米")),
    Indicator("e_cod", "化学需氧量排放量", "E", "quantitative", ("化学需氧量", "COD", "COD排放"), ("吨", "千克")),
    Indicator("e_ammonia_nitrogen", "氨氮排放量", "E", "quantitative", ("氨氮", "氨氮排放"), ("吨", "千克")),
    Indicator("e_waste_total", "废弃物产生量", "E", "quantitative", ("废弃物产生量", "废弃物总量", "固体废弃物", "固废"), ("吨", "千克")),
    Indicator("e_hazardous_waste", "危险废弃物产生量", "E", "quantitative", ("危险废弃物", "危废", "有害废弃物"), ("吨", "千克")),
    Indicator("e_nonhazardous_waste", "一般废弃物产生量", "E", "quantitative", ("一般废弃物", "无害废弃物", "非危险废弃物"), ("吨", "千克")),
    Indicator("e_waste_recycling", "废弃物回收利用量", "E", "quantitative", ("废弃物回收", "回收利用", "资源化利用", "回收率"), ("吨", "%")),
    Indicator("e_air_pollutants", "大气污染物排放", "E", "quantitative", ("大气污染物", "废气排放", "二氧化硫", "氮氧化物", "颗粒物"), ("吨", "千克")),
    Indicator("e_so2", "二氧化硫排放量", "E", "quantitative", ("二氧化硫", "SO2", "SO₂"), ("吨", "千克")),
    Indicator("e_nox", "氮氧化物排放量", "E", "quantitative", ("氮氧化物", "NOx", "NOX"), ("吨", "千克")),
    Indicator("e_voc", "挥发性有机物排放量", "E", "quantitative", ("挥发性有机物", "VOCs", "VOC"), ("吨", "千克")),
    Indicator("e_particulate", "颗粒物排放量", "E", "quantitative", ("颗粒物", "烟尘", "粉尘"), ("吨", "千克")),
    Indicator("e_environmental_investment", "环保投入", "E", "quantitative", ("环保投入", "环境保护投入", "环保投资", "环境治理投入"), ("万元", "元")),
    Indicator("e_environmental_penalty", "环境处罚", "E", "qualitative", ("环境处罚", "环保处罚", "环境违法", "环境违规")),
    Indicator("e_biodiversity", "生物多样性保护", "E", "qualitative", ("生物多样性", "生态保护", "生态修复", "自然保护")),
    Indicator("e_green_product", "绿色产品与服务", "E", "qualitative", ("绿色产品", "绿色服务", "绿色金融", "绿色技术")),
    Indicator("e_green_office", "绿色办公", "E", "qualitative", ("绿色办公", "无纸化办公", "节能办公", "低碳办公")),
    Indicator("s_employee_total", "员工总数", "S", "quantitative", ("员工总数", "员工总人数", "员工数量", "雇员总数"), ("人",)),
    Indicator("s_employee_gender", "女性员工人数或占比", "S", "quantitative", ("女性员工", "女员工", "女性雇员", "女性占比"), ("人", "%")),
    Indicator("s_employee_turnover", "员工流失率", "S", "quantitative", ("员工流失率", "离职率", "员工离职"), ("%",)),
    Indicator("s_new_hires", "新增员工人数", "S", "quantitative", ("新增员工", "新进员工", "新聘员工", "招聘人数"), ("人",)),
    Indicator("s_training", "员工培训", "S", "quantitative", ("员工培训", "培训总时长", "培训投入", "培训小时"), ("小时", "万元")),
    Indicator("s_training_coverage", "员工培训覆盖率", "S", "quantitative", ("培训覆盖率", "受训员工比例", "员工受训率"), ("%",)),
    Indicator("s_training_average", "人均培训时长", "S", "quantitative", ("人均培训时长", "平均培训时长", "每名员工培训"), ("小时",)),
    Indicator("s_compensation_benefits", "薪酬福利", "S", "qualitative", ("薪酬福利", "员工福利", "福利体系", "薪酬体系")),
    Indicator("s_social_insurance", "社会保险覆盖", "S", "qualitative", ("社会保险", "五险一金", "社保覆盖", "住房公积金")),
    Indicator("s_employee_rights", "员工权益保障", "S", "qualitative", ("员工权益", "劳动权益", "民主管理", "员工沟通")),
    Indicator("s_diversity_equal_opportunity", "多元化与平等机会", "S", "qualitative", ("多元化", "平等机会", "反歧视", "包容性")),
    Indicator("s_occupational_health", "职业健康", "S", "qualitative", ("职业健康", "职业病防治", "职业卫生", "健康管理")),
    Indicator("s_safety", "安全生产", "S", "qualitative", ("安全生产", "职业健康", "安全投入", "安全标准化")),
    Indicator("s_work_injury", "工伤事故", "S", "quantitative", ("工伤", "因工伤亡", "工伤事故", "损失工时"), ("起", "人", "小时")),
    Indicator("s_safety_training", "安全培训", "S", "quantitative", ("安全培训", "安全教育", "应急演练", "安全生产培训"), ("次", "人次", "小时")),
    Indicator("s_product_quality", "产品质量管理", "S", "qualitative", ("产品质量", "质量管理", "质量控制", "质量体系")),
    Indicator("s_customer_satisfaction", "客户满意度", "S", "quantitative", ("客户满意度", "顾客满意度", "满意度调查"), ("%", "分")),
    Indicator("s_customer_complaints", "客户投诉", "S", "quantitative", ("客户投诉", "投诉处理", "投诉数量", "投诉率"), ("件", "%")),
    Indicator("s_data_security", "数据安全与隐私保护", "S", "qualitative", ("数据安全", "隐私保护", "信息安全", "客户隐私")),
    Indicator("s_research_development", "研发投入", "S", "quantitative", ("研发投入", "研发费用", "研发支出", "研发经费"), ("万元", "元", "%")),
    Indicator("s_patents", "专利数量", "S", "quantitative", ("专利", "发明专利", "授权专利", "知识产权"), ("项", "件")),
    Indicator("s_supplier", "供应商管理", "S", "qualitative", ("供应商管理", "供应链管理", "供应商审核", "责任供应链")),
    Indicator("s_supplier_count", "供应商数量", "S", "quantitative", ("供应商数量", "供应商总数", "合作供应商"), ("家",)),
    Indicator("s_supplier_esg_assessment", "供应商 ESG 评估", "S", "qualitative", ("供应商ESG", "供应商环境", "供应商社会责任", "供应商评估")),
    Indicator("s_local_procurement", "本地采购", "S", "quantitative", ("本地采购", "当地采购", "本地供应商"), ("万元", "%")),
    Indicator("s_community_investment", "公益慈善投入", "S", "quantitative", ("公益投入", "慈善捐赠", "社会公益", "社区投资"), ("万元", "元")),
    Indicator("s_volunteer_hours", "志愿服务时长", "S", "quantitative", ("志愿服务", "志愿者活动", "志愿服务时长"), ("小时", "人次")),
    Indicator("s_rural_revitalization", "乡村振兴", "S", "qualitative", ("乡村振兴", "扶贫", "助农", "共同富裕")),
    Indicator("s_human_rights", "人权与劳工准则", "S", "qualitative", ("人权", "童工", "强迫劳动", "劳工准则")),
    Indicator("s_accessibility", "无障碍与普惠服务", "S", "qualitative", ("无障碍", "普惠服务", "适老化", "弱势群体")),
    Indicator("g_board_size", "董事会人数", "G", "quantitative", ("董事会人数", "董事人数", "董事会成员"), ("人",)),
    Indicator("g_independent_director_ratio", "独立董事占比", "G", "quantitative", ("独立董事占比", "独立董事", "独董比例"), ("%", "人")),
    Indicator("g_board_diversity", "董事会多元化", "G", "quantitative", ("女性董事", "董事会多元化", "董事会成员", "独立董事占比"), ("%", "人")),
    Indicator("g_female_executive_ratio", "女性高管占比", "G", "quantitative", ("女性高管", "女高管", "高级管理人员女性", "管理层女性"), ("%", "人")),
    Indicator("g_board_meetings", "董事会会议次数", "G", "quantitative", ("董事会会议", "召开董事会", "董事会召开"), ("次",)),
    Indicator("g_shareholder_meetings", "股东大会次数", "G", "quantitative", ("股东大会", "股东会", "召开股东大会"), ("次",)),
    Indicator("g_esg_governance", "ESG 治理架构", "G", "qualitative", ("ESG治理", "可持续发展治理", "ESG委员会", "ESG工作小组")),
    Indicator("g_esg_strategy", "ESG 战略目标", "G", "qualitative", ("ESG战略", "可持续发展战略", "ESG目标", "可持续发展目标")),
    Indicator("g_stakeholder_communication", "利益相关方沟通", "G", "qualitative", ("利益相关方", "相关方沟通", "实质性议题", "重要性议题")),
    Indicator("g_materiality_assessment", "实质性议题评估", "G", "qualitative", ("实质性议题", "重要性评估", "议题矩阵", "双重重要性")),
    Indicator("g_anti_corruption", "反腐败机制", "G", "qualitative", ("反腐败", "反腐", "廉洁", "反商业贿赂", "商业道德")),
    Indicator("g_anti_corruption_training", "反腐败培训", "G", "quantitative", ("反腐败培训", "廉洁培训", "商业道德培训", "合规培训"), ("次", "人次", "小时")),
    Indicator("g_whistleblowing", "举报与申诉机制", "G", "qualitative", ("举报机制", "投诉举报", "申诉机制", " whistleblowing")),
    Indicator("g_compliance_management", "合规管理", "G", "qualitative", ("合规管理", "合规体系", "合规风险", "依法合规")),
    Indicator("g_risk_management", "风险管理体系", "G", "qualitative", ("风险管理", "内控体系", "内部控制", "风险防控")),
    Indicator("g_business_ethics", "商业道德", "G", "qualitative", ("商业道德", "诚信经营", "道德准则", "职业道德")),
    Indicator("g_tax_transparency", "税务透明", "G", "qualitative", ("税务透明", "依法纳税", "税务合规", "纳税")),
    Indicator("g_information_disclosure", "信息披露", "G", "qualitative", ("信息披露", "披露透明", "投资者关系", "公告披露")),
    Indicator("g_investor_relations", "投资者关系", "G", "qualitative", ("投资者关系", "投资者沟通", "业绩说明会", "投资者交流")),
    Indicator("g_cybersecurity_governance", "网络安全治理", "G", "qualitative", ("网络安全", "信息安全治理", "网络安全管理", "数据治理")),
    Indicator("g_audit_committee", "审计委员会", "G", "qualitative", ("审计委员会", "审计与风险委员会", "内部审计")),
    Indicator("g_remuneration_committee", "薪酬委员会", "G", "qualitative", ("薪酬委员会", "薪酬与考核委员会", "董事薪酬")),
    Indicator("g_nomination_committee", "提名委员会", "G", "qualitative", ("提名委员会", "董事提名", "提名机制")),
    Indicator("g_related_party_transactions", "关联交易管理", "G", "qualitative", ("关联交易", "关联方交易", "关联交易管理")),
    Indicator("g_intellectual_property_protection", "知识产权保护机制", "G", "qualitative", ("知识产权保护", "知识产权管理", "专利保护", "商标保护")),
    Indicator("g_party_building", "党建工作", "G", "qualitative", ("党建", "党组织", "党的建设", "党委")),
]

DEMO_INDICATORS = FORMAL_INDICATORS[:12]
